# Javascript Angular CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
version: 2
jobs:
  build:
    <<: *defaults
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11-browsers

    working_directory: ~/ng-ngrx-forms-demo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install-dependencies
          command: yarn install

      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules

      - run:
          name: Build
          command: yarn build

      - persist_to_workspace:
          root: dist
          paths:
            - dist

      - run:
          name: Code Quality
          command: yarn lint

      #- run:
      #    name: Test
      #    command: yarn test

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /dist

      - run:
          name: Deploy App to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2

  angular:
    jobs:
      - build
      - deploy:
          requires:
            - build
