# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11-browsers

    working_directory: ~/ng-ngrx-forms-demo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install-dependencies
          command: yarn install

      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: build
          command: yarn ng -- build --prod --aot --no-progress

      - store_artifacts:
          path: dist
          prefix: dist

      - run:
          name: lint
          command: yarn lint -- --formatters-dir ./tslint-formatters --format junit -o tslint.xml
      - store_artifacts:
          path: tslint.xml
          prefix: lint

      - run:
          name: test
          commoand: yarn test --single-run --no-progress
      - store_artifcats:
          path: test-results.xml
          prefix: test
